Repository ElemeFE/element, pull requests merged in 2018-03, with the labels that each got.

#9894 Select: make select click show options layer not focus (#9821)
  packages/select/src/select.vue
  test/unit/specs/select.spec.js
Labels: need: changes, status: don't merge

#9320 Slider: Touch events added to support mobile devices
  packages/slider/src/button.vue
Labels: need: changes

#10170 ColorPicker: add predefine colors(#8702)
  examples/docs/en-US/color-picker.md
  examples/docs/es/color-picker.md
  examples/docs/zh-CN/color-picker.md
  packages/color-picker/src/color.js
  packages/color-picker/src/components/picker-dropdown.vue
  packages/color-picker/src/components/predefine.vue
  packages/color-picker/src/main.vue
  packages/theme-chalk/src/color-picker.scss
  test/unit/specs/color-picker.spec.js
Labels: need: changes, need: test case
