Repository ElemeFE/element, pull requests merged in 2019-04, with the labels that each got.

#15051 Rate: add custom colors and icon-classes by passing a object
  examples/demo-styles/rate.scss
  examples/docs/en-US/rate.md
  examples/docs/es/rate.md
  examples/docs/fr-FR/rate.md
  examples/docs/zh-CN/rate.md
  packages/rate/src/main.vue
  src/utils/types.js
  test/unit/specs/rate.spec.js
  types/rate.d.ts
Labels: kiwi

#15055 Divider: add divider component
  components.json
  examples/demo-styles/divider.scss
  examples/demo-styles/index.scss
  examples/docs/en-US/divider.md
  examples/docs/es/divider.md
  examples/docs/fr-FR/divider.md
  examples/docs/zh-CN/divider.md
  examples/nav.config.json
  packages/divider/index.js
  packages/divider/src/main.js
  packages/theme-chalk/src/divider.scss
  packages/theme-chalk/src/index.scss
  src/index.js
  test/unit/specs/divider.spec.js
  types/divider.d.ts
  types/element-ui.d.ts
Labels: kiwi

#15041 Alert: Add dark theme
  examples/docs/en-US/alert.md
  examples/docs/es/alert.md
  examples/docs/fr-FR/alert.md
  examples/docs/zh-CN/alert.md
  packages/alert/src/main.vue
  packages/theme-chalk/src/alert.scss
  test/unit/specs/alert.spec.js
  types/alert.d.ts
Labels: kiwi

#15076 Collapse: collapse item can be disabled
  examples/docs/en-US/collapse.md
  examples/docs/es/collapse.md
  examples/docs/fr-FR/collapse.md
  examples/docs/zh-CN/collapse.md
  packages/collapse/src/collapse-item.vue
  packages/theme-chalk/src/collapse.scss
  types/collapse-item.d.ts
Labels: kiwi

#15122 Carousel: add direction attribute and support vertical direction
  examples/demo-styles/carousel.scss
  examples/docs/en-US/carousel.md
  examples/docs/es/carousel.md
  examples/docs/fr-FR/carousel.md
  examples/docs/zh-CN/carousel.md
  packages/carousel/src/item.vue
  packages/carousel/src/main.vue
  packages/theme-chalk/src/carousel.scss
  src/utils/util.js
  test/unit/specs/carousel.spec.js
  types/carousel.d.ts
Labels: kiwi

#15096 Pagination: add hide-on-single-page attribute
  examples/docs/en-US/pagination.md
  examples/docs/es/pagination.md
  examples/docs/fr-FR/pagination.md
  examples/docs/zh-CN/pagination.md
  packages/pagination/src/pagination.js
  test/unit/specs/pagination.spec.js
  types/pagination.d.ts
Labels: kiwi

#15133 Slider: add marks attribute
  examples/docs/en-US/slider.md
  examples/docs/es/slider.md
  examples/docs/fr-FR/slider.md
  examples/docs/zh-CN/slider.md
  packages/slider/src/main.vue
  packages/slider/src/marker.js
  packages/theme-chalk/src/slider.scss
  test/unit/specs/slider.spec.js
  types/slider.d.ts
Labels: kiwi

#15075 Input: add show-word-count attribute
  examples/docs/en-US/input.md
  examples/docs/es/input.md
  examples/docs/fr-FR/input.md
  examples/docs/zh-CN/input.md
  packages/input/src/input.vue
  packages/theme-chalk/src/input.scss
  test/unit/specs/input.spec.js
  types/input.d.ts
Labels: kiwi

#15052 Link: add link component
  components.json
  examples/docs/en-US/link.md
  examples/docs/es/link.md
  examples/docs/fr-FR/link.md
  examples/docs/zh-CN/link.md
  examples/nav.config.json
  packages/link/index.js
  packages/link/src/main.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/index.scss
  packages/theme-chalk/src/link.scss
  src/index.js
  test/unit/specs/link.spec.js
  types/link.d.ts
Labels: kiwi

#14881 Tree: performance optimization
  packages/tree/src/model/node.js
  packages/tree/src/model/tree-store.js
  packages/tree/src/tree-node.vue
  types/tree.d.ts
Labels: component: tree

#15050 InputNumber: add step-strictly attribute
  examples/docs/en-US/input-number.md
  examples/docs/es/input-number.md
  examples/docs/fr-FR/input-number.md
  examples/docs/zh-CN/input-number.md
  packages/input-number/src/input-number.vue
  test/unit/specs/input-number.spec.js
  types/input-number.d.ts
Labels: kiwi

#14660 Table: equal behaviour for height and max-height
  packages/table/src/table.vue
Labels: component: table
