Repository ElemeFE/element, pull requests merged in 2019-05, with the labels that each got.

#15295 Input-Number: Fix precision problem (#15292)
  packages/input-number/src/input-number.vue
Labels: status: discussion

#15412 Theme: Add popup background design token (Message Dialog)
  examples/components/theme-configurator/index.vue
  packages/theme-chalk/src/common/popup.scss
  packages/theme-chalk/src/common/var.scss
Labels: kiwi, pointer

#15725 Tag: add prop effect.
  examples/demo-styles/tag.scss
  examples/docs/en-US/tag.md
  examples/docs/es/tag.md
  examples/docs/fr-FR/tag.md
  examples/docs/zh-CN/tag.md
  packages/tag/src/tag.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/tag.scss
  test/unit/specs/tag.spec.js
  types/tag.d.ts
Labels: kiwi

#15567 infiniteScroll: add infiniteScroll component
  build/bin/build-entry.js
  components.json
  examples/demo-styles/index.scss
  examples/demo-styles/infiniteScroll.scss
  examples/docs/en-US/infiniteScroll.md
  examples/docs/es/infiniteScroll.md
  examples/docs/fr-FR/infiniteScroll.md
  examples/docs/zh-CN/infiniteScroll.md
  examples/nav.config.json
  packages/infiniteScroll/index.js
  packages/infiniteScroll/src/main.js
  src/index.js
  src/utils/types.js
  test/unit/specs/infiniteScroll.spec.js
  types/element-ui.d.ts
  types/infiniteScroll.d.ts
Labels: kiwi

#15695 Tabs: left align title when type is card
  packages/theme-chalk/src/tabs.scss
Labels: kiwi

#15541 Backtop: Add backtop component
  components.json
  examples/docs/en-US/backtop.md
  examples/docs/es/backtop.md
  examples/docs/fr-FR/backtop.md
  examples/docs/zh-CN/backtop.md
  examples/nav.config.json
  examples/pages/template/component.tpl
  packages/backtop/index.js
  packages/backtop/src/main.vue
  packages/theme-chalk/src/backtop.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/index.scss
  src/index.js
  test/unit/specs/backtop.spec.js
  types/backtop.d.ts
  types/element-ui.d.ts
Labels: kiwi

#11867 Progress: add dashboard progress bar
  examples/docs/en-US/progress.md
  examples/docs/es/progress.md
  examples/docs/fr-FR/progress.md
  examples/docs/zh-CN/progress.md
  packages/progress/src/progress.vue
  packages/theme-chalk/src/progress.scss
  test/unit/specs/progress.spec.js
  types/progress.d.ts
Labels: kiwi

#15639 Message: display in stack mode
  examples/docs/en-US/message.md
  examples/docs/es/message.md
  examples/docs/fr-FR/message.md
  examples/docs/zh-CN/message.md
  packages/message/src/main.js
  packages/message/src/main.vue
  packages/theme-chalk/src/message.scss
Labels: kiwi
